### ISSUE TITLE
SwiftyBeaver

### ISSUE THREAD

**Issue by IsaiahJTurner** [devmjun/devmjun.github.io#45]
Your project uses SwiftyBeaver. SwiftyBeaver has security vulnerabilities that you may wish to address. Consider removing SwiftyBeaver if your app transmits PII. https://github.com/SwiftyBeaver/SwiftyBeaver/issues/453

**Comment by devmjun** [comment]
It's a little late, but thanks for the message. I'll check it out 
Thank you :)
